name: 'Get Version Run Number'
description: 'Extracts the version from github.ref.runNumber'
author: 'Nivaes'
outputs:
  version:
    description: 'The version on run number'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
